version: "3"
services:
  crawler-homes:
    image: "crawler-homes-go:1.0.0"
    deploy:
      replicas: 1
    environment:
      - WS_SESSION_ID=1c4b5dfd850141947303ddd530bf254d
      - WS_ENDPOINT=ws://pw-server:12345
      - NATS_SERVER_URL=nats-server:4222
    depends_on:
      - pw-server
  pw-server:
    image: "pw-server-go:1.0.0"
    ports:
      - 12345:12345
    deploy:
      replicas: 1
  scanner-homes:
    image: "scanner-homes-go:1.0.0"
    deploy:
      replicas: 1
    environment:
      - WS_SESSION_ID=1c4b5dfd850141947303ddd530bf254d
      - WS_ENDPOINT=ws://pw-server:12345
      - NATS_SERVER_URL=nats-server:4222
    depends_on:
      - pw-server
      - nats-server
  notifier:
    image: "notifier-go:1.0.0"
    deploy:
      replicas: 1
    environment:
      - NATS_SERVER_URL=nats-server:4222
      - LINE_NOTIFY_TOKEN=${LINE_NOTIFY_TOKEN}
    depends_on:
      - nats-server
  checker:
    image: "checker-go:1.0.0"
    deploy:
      replicas: 1
    environment:
      - REDIS_SERVER_URL=redis-server:6379
    depends_on:
      - redis-server
  nats-server:
    image: "nats:2.7.4"
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: -js
  redis-server:
    image: "redis:7-alpine"
    ports:
      - 6379:6379
