version: "3"
services:
  main:
    image: "main-go:1.0.0"
    deploy:
      replicas: 1
    environment:
      - NATS_SERVER_URL=nats-server:4222
    depends_on:
      - crawler-homes
      - scanner-homes
  crawler-homes:
    image: "crawler-homes-go:1.0.0"
    deploy:
      replicas: 1
    environment:
      - WS_SESSION_ID=aef0492dd5c155753c119fa09dd92e4e
      - WS_ENDPOINT=ws://pw-server-1:12345
      - NATS_SERVER_URL=nats-server:4222
    depends_on:
      - pw-server-1
  pw-server-1:
    image: "pw-server-go:1.0.0"
    deploy:
      replicas: 1
    ports:
      - 12345:12345
    command: "12345"
  pw-server-2:
    image: "pw-server-go:1.0.0"
    deploy:
      replicas: 1
    ports:
      - 23456:23456
    command: "23456"
  scanner-homes:
    image: "scanner-homes-go:1.0.0"
    deploy:
      replicas: 1
    environment:
      - WS_SESSION_ID=73ba25336acebaae9a06b8bcbb696de2
      - WS_ENDPOINT=ws://pw-server-2:23456
      - NATS_SERVER_URL=nats-server:4222
    depends_on:
      - pw-server-2
      - nats-server
  notifier:
    image: "notifier-go:1.0.0"
    deploy:
      replicas: 1
    environment:
      - NATS_SERVER_URL=nats-server:4222
      - LINE_NOTIFY_TOKEN=${LINE_NOTIFY_TOKEN}
    depends_on:
      - nats-server
  checker:
    image: "checker-go:1.0.0"
    deploy:
      replicas: 1
    environment:
      - REDIS_SERVER_URL=redis-server:6379
    depends_on:
      - redis-server
  nats-server:
    image: "nats:2.7.4"
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: -js
  redis-server:
    image: "redis:7-alpine"
    ports:
      - 6379:6379
