// Protocol Buffersのバージョンを指定

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: checker.proto

// パッケージを指定

package checker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckStatus int32

const (
	CheckStatus_NOT_USED          CheckStatus = 0
	CheckStatus_SATISFIED         CheckStatus = 1
	CheckStatus_NOT_SATISFIED     CheckStatus = 2
	CheckStatus_NOT_INSPECTED     CheckStatus = 3
	CheckStatus_ALREADY_NOTIFIED  CheckStatus = 4
	CheckStatus_ALREADY_INSPECTED CheckStatus = 5
)

// Enum value maps for CheckStatus.
var (
	CheckStatus_name = map[int32]string{
		0: "NOT_USED",
		1: "SATISFIED",
		2: "NOT_SATISFIED",
		3: "NOT_INSPECTED",
		4: "ALREADY_NOTIFIED",
		5: "ALREADY_INSPECTED",
	}
	CheckStatus_value = map[string]int32{
		"NOT_USED":          0,
		"SATISFIED":         1,
		"NOT_SATISFIED":     2,
		"NOT_INSPECTED":     3,
		"ALREADY_NOTIFIED":  4,
		"ALREADY_INSPECTED": 5,
	}
)

func (x CheckStatus) Enum() *CheckStatus {
	p := new(CheckStatus)
	*p = x
	return p
}

func (x CheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_checker_proto_enumTypes[0].Descriptor()
}

func (CheckStatus) Type() protoreflect.EnumType {
	return &file_checker_proto_enumTypes[0]
}

func (x CheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckStatus.Descriptor instead.
func (CheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{0}
}

type CheckByUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CheckByUrlRequest) Reset() {
	*x = CheckByUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckByUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckByUrlRequest) ProtoMessage() {}

func (x *CheckByUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckByUrlRequest.ProtoReflect.Descriptor instead.
func (*CheckByUrlRequest) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{0}
}

func (x *CheckByUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CheckByUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result CheckStatus `protobuf:"varint,1,opt,name=result,proto3,enum=checker.CheckStatus" json:"result,omitempty"`
}

func (x *CheckByUrlResponse) Reset() {
	*x = CheckByUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckByUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckByUrlResponse) ProtoMessage() {}

func (x *CheckByUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckByUrlResponse.ProtoReflect.Descriptor instead.
func (*CheckByUrlResponse) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{1}
}

func (x *CheckByUrlResponse) GetResult() CheckStatus {
	if x != nil {
		return x.Result
	}
	return CheckStatus_NOT_USED
}

type CheckByRoomDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail *RoomDetail `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *CheckByRoomDetailRequest) Reset() {
	*x = CheckByRoomDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckByRoomDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckByRoomDetailRequest) ProtoMessage() {}

func (x *CheckByRoomDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckByRoomDetailRequest.ProtoReflect.Descriptor instead.
func (*CheckByRoomDetailRequest) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{2}
}

func (x *CheckByRoomDetailRequest) GetDetail() *RoomDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type CheckByRoomDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result CheckStatus `protobuf:"varint,1,opt,name=result,proto3,enum=checker.CheckStatus" json:"result,omitempty"`
}

func (x *CheckByRoomDetailResponse) Reset() {
	*x = CheckByRoomDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckByRoomDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckByRoomDetailResponse) ProtoMessage() {}

func (x *CheckByRoomDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckByRoomDetailResponse.ProtoReflect.Descriptor instead.
func (*CheckByRoomDetailResponse) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{3}
}

func (x *CheckByRoomDetailResponse) GetResult() CheckStatus {
	if x != nil {
		return x.Result
	}
	return CheckStatus_NOT_USED
}

type UpdateCheckStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail *RoomDetail `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	Status CheckStatus `protobuf:"varint,2,opt,name=status,proto3,enum=checker.CheckStatus" json:"status,omitempty"`
}

func (x *UpdateCheckStatusRequest) Reset() {
	*x = UpdateCheckStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCheckStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckStatusRequest) ProtoMessage() {}

func (x *UpdateCheckStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCheckStatusRequest) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCheckStatusRequest) GetDetail() *RoomDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *UpdateCheckStatusRequest) GetStatus() CheckStatus {
	if x != nil {
		return x.Status
	}
	return CheckStatus_NOT_USED
}

type UpdateCheckStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result CheckStatus `protobuf:"varint,1,opt,name=result,proto3,enum=checker.CheckStatus" json:"result,omitempty"`
}

func (x *UpdateCheckStatusResponse) Reset() {
	*x = UpdateCheckStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCheckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckStatusResponse) ProtoMessage() {}

func (x *UpdateCheckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateCheckStatusResponse) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCheckStatusResponse) GetResult() CheckStatus {
	if x != nil {
		return x.Result
	}
	return CheckStatus_NOT_USED
}

var File_checker_proto protoreflect.FileDescriptor

var file_checker_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x1a, 0x10, 0x72, 0x6f, 0x6f, 0x6d, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x11, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x42, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x42, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x79, 0x55, 0x72, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3f, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x79,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x49, 0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42,
	0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x6d, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x49, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x7d, 0x0a, 0x0b, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f,
	0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x41, 0x54, 0x49,
	0x53, 0x46, 0x49, 0x45, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54, 0x5f, 0x53,
	0x41, 0x54, 0x49, 0x53, 0x46, 0x49, 0x45, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f,
	0x54, 0x5f, 0x49, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x14, 0x0a,
	0x10, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x49,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x05, 0x32, 0x88, 0x02, 0x0a, 0x07, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42,
	0x79, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x42, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x42, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a,
	0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21,
	0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x6b, 0x69, 0x61, 0x2f, 0x72, 0x65, 0x6e, 0x74, 0x2d, 0x77,
	0x61, 0x74, 0x63, 0x68, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_checker_proto_rawDescOnce sync.Once
	file_checker_proto_rawDescData = file_checker_proto_rawDesc
)

func file_checker_proto_rawDescGZIP() []byte {
	file_checker_proto_rawDescOnce.Do(func() {
		file_checker_proto_rawDescData = protoimpl.X.CompressGZIP(file_checker_proto_rawDescData)
	})
	return file_checker_proto_rawDescData
}

var file_checker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_checker_proto_goTypes = []interface{}{
	(CheckStatus)(0),                  // 0: checker.CheckStatus
	(*CheckByUrlRequest)(nil),         // 1: checker.CheckByUrlRequest
	(*CheckByUrlResponse)(nil),        // 2: checker.CheckByUrlResponse
	(*CheckByRoomDetailRequest)(nil),  // 3: checker.CheckByRoomDetailRequest
	(*CheckByRoomDetailResponse)(nil), // 4: checker.CheckByRoomDetailResponse
	(*UpdateCheckStatusRequest)(nil),  // 5: checker.UpdateCheckStatusRequest
	(*UpdateCheckStatusResponse)(nil), // 6: checker.UpdateCheckStatusResponse
	(*RoomDetail)(nil),                // 7: RoomDetail
}
var file_checker_proto_depIdxs = []int32{
	0, // 0: checker.CheckByUrlResponse.result:type_name -> checker.CheckStatus
	7, // 1: checker.CheckByRoomDetailRequest.detail:type_name -> RoomDetail
	0, // 2: checker.CheckByRoomDetailResponse.result:type_name -> checker.CheckStatus
	7, // 3: checker.UpdateCheckStatusRequest.detail:type_name -> RoomDetail
	0, // 4: checker.UpdateCheckStatusRequest.status:type_name -> checker.CheckStatus
	0, // 5: checker.UpdateCheckStatusResponse.result:type_name -> checker.CheckStatus
	1, // 6: checker.Checker.CheckByUrl:input_type -> checker.CheckByUrlRequest
	3, // 7: checker.Checker.CheckByRoomDetail:input_type -> checker.CheckByRoomDetailRequest
	5, // 8: checker.Checker.UpdateCheckStatus:input_type -> checker.UpdateCheckStatusRequest
	2, // 9: checker.Checker.CheckByUrl:output_type -> checker.CheckByUrlResponse
	4, // 10: checker.Checker.CheckByRoomDetail:output_type -> checker.CheckByRoomDetailResponse
	6, // 11: checker.Checker.UpdateCheckStatus:output_type -> checker.UpdateCheckStatusResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_checker_proto_init() }
func file_checker_proto_init() {
	if File_checker_proto != nil {
		return
	}
	file_roomdetail_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_checker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckByUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckByUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckByRoomDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckByRoomDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCheckStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCheckStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_checker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checker_proto_goTypes,
		DependencyIndexes: file_checker_proto_depIdxs,
		EnumInfos:         file_checker_proto_enumTypes,
		MessageInfos:      file_checker_proto_msgTypes,
	}.Build()
	File_checker_proto = out.File
	file_checker_proto_rawDesc = nil
	file_checker_proto_goTypes = nil
	file_checker_proto_depIdxs = nil
}
