// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: roomdetail.proto

package checker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomType int32

const (
	RoomType_RENT RoomType = 0
	RoomType_SALE RoomType = 1
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "RENT",
		1: "SALE",
	}
	RoomType_value = map[string]int32{
		"RENT": 0,
		"SALE": 1,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_roomdetail_proto_enumTypes[0].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_roomdetail_proto_enumTypes[0]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_roomdetail_proto_rawDescGZIP(), []int{0}
}

type FloorLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorLevel    int32 `protobuf:"varint,1,opt,name=floorLevel,proto3" json:"floorLevel,omitempty"`
	FloorTopLevel int32 `protobuf:"varint,2,opt,name=floorTopLevel,proto3" json:"floorTopLevel,omitempty"`
}

func (x *FloorLevel) Reset() {
	*x = FloorLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomdetail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloorLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloorLevel) ProtoMessage() {}

func (x *FloorLevel) ProtoReflect() protoreflect.Message {
	mi := &file_roomdetail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloorLevel.ProtoReflect.Descriptor instead.
func (*FloorLevel) Descriptor() ([]byte, []int) {
	return file_roomdetail_proto_rawDescGZIP(), []int{0}
}

func (x *FloorLevel) GetFloorLevel() int32 {
	if x != nil {
		return x.FloorLevel
	}
	return 0
}

func (x *FloorLevel) GetFloorTopLevel() int32 {
	if x != nil {
		return x.FloorTopLevel
	}
	return 0
}

type RoomDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string      `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Price      float64     `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Size       float64     `protobuf:"fixed64,3,opt,name=size,proto3" json:"size,omitempty"`
	FloorLevel *FloorLevel `protobuf:"bytes,4,opt,name=floorLevel,proto3" json:"floorLevel,omitempty"`
	Address    string      `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	BuiltYear  int32       `protobuf:"varint,6,opt,name=builtYear,proto3" json:"builtYear,omitempty"`
	Type       RoomType    `protobuf:"varint,7,opt,name=type,proto3,enum=RoomType" json:"type,omitempty"`
	IsPetOK    bool        `protobuf:"varint,8,opt,name=isPetOK,proto3" json:"isPetOK,omitempty"`
}

func (x *RoomDetail) Reset() {
	*x = RoomDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomdetail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDetail) ProtoMessage() {}

func (x *RoomDetail) ProtoReflect() protoreflect.Message {
	mi := &file_roomdetail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDetail.ProtoReflect.Descriptor instead.
func (*RoomDetail) Descriptor() ([]byte, []int) {
	return file_roomdetail_proto_rawDescGZIP(), []int{1}
}

func (x *RoomDetail) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RoomDetail) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RoomDetail) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RoomDetail) GetFloorLevel() *FloorLevel {
	if x != nil {
		return x.FloorLevel
	}
	return nil
}

func (x *RoomDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RoomDetail) GetBuiltYear() int32 {
	if x != nil {
		return x.BuiltYear
	}
	return 0
}

func (x *RoomDetail) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_RENT
}

func (x *RoomDetail) GetIsPetOK() bool {
	if x != nil {
		return x.IsPetOK
	}
	return false
}

var File_roomdetail_proto protoreflect.FileDescriptor

var file_roomdetail_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x6f, 0x6f, 0x6d, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x52, 0x0a, 0x0a, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x24, 0x0a, 0x0d, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x54, 0x6f, 0x70, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x54, 0x6f,
	0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xe6, 0x01, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x75, 0x69, 0x6c,
	0x74, 0x59, 0x65, 0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x75, 0x69,
	0x6c, 0x74, 0x59, 0x65, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x50, 0x65, 0x74, 0x4f, 0x4b,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x50, 0x65, 0x74, 0x4f, 0x4b, 0x2a,
	0x1e, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x52,
	0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x42,
	0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65,
	0x6b, 0x69, 0x61, 0x2f, 0x72, 0x65, 0x6e, 0x74, 0x2d, 0x77, 0x61, 0x74, 0x63, 0x68, 0x2d, 0x67,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_roomdetail_proto_rawDescOnce sync.Once
	file_roomdetail_proto_rawDescData = file_roomdetail_proto_rawDesc
)

func file_roomdetail_proto_rawDescGZIP() []byte {
	file_roomdetail_proto_rawDescOnce.Do(func() {
		file_roomdetail_proto_rawDescData = protoimpl.X.CompressGZIP(file_roomdetail_proto_rawDescData)
	})
	return file_roomdetail_proto_rawDescData
}

var file_roomdetail_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_roomdetail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_roomdetail_proto_goTypes = []interface{}{
	(RoomType)(0),      // 0: RoomType
	(*FloorLevel)(nil), // 1: FloorLevel
	(*RoomDetail)(nil), // 2: RoomDetail
}
var file_roomdetail_proto_depIdxs = []int32{
	1, // 0: RoomDetail.floorLevel:type_name -> FloorLevel
	0, // 1: RoomDetail.type:type_name -> RoomType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_roomdetail_proto_init() }
func file_roomdetail_proto_init() {
	if File_roomdetail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_roomdetail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloorLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomdetail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roomdetail_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_roomdetail_proto_goTypes,
		DependencyIndexes: file_roomdetail_proto_depIdxs,
		EnumInfos:         file_roomdetail_proto_enumTypes,
		MessageInfos:      file_roomdetail_proto_msgTypes,
	}.Build()
	File_roomdetail_proto = out.File
	file_roomdetail_proto_rawDesc = nil
	file_roomdetail_proto_goTypes = nil
	file_roomdetail_proto_depIdxs = nil
}
